### ISSUE TITLE
next problem

### ISSUE THREAD

**Issue by 0x72D0** [0x72D0/JavaOverflow#23]
nommerEntity.txt next question bug

**Comment by rafeu** [comment]
Précisément: La question d'initialiser un int à 9 est répété et ne donne pas de points.

De plus, la variable ne peut pas ếtre nommer avec plus d'une lettre (xx ne marche pas, mais x oui)

**Comment by 0x72D0** [comment]
probleme a moitier regler, le programme passe maintenant a la question suivante, mais la variable ne peut pas ete nommer avec plus d'une lettre (probleme lier aux regex)

**Comment by 0x72D0** [comment]
note: lorsqu'on met le numero de l'issue dans un commit ca le ferme automatiquement
