### ISSUE TITLE
Options-Duy

### ISSUE THREAD

**Issue by 0x72D0** [0x72D0/JavaOverflow#31]
Lorsqu' on entre une taille de police seulement et on click sur le bouton "utiliser par ...",
on ne sort pas des options on n'a pas non plus de fenetre de confirmation.
a ajouter ! 

on devrait avoir un bouton quitter aussi.

couler de ppolice: donnons des choix? genre une liste deroulante

**Comment by BonGiovi44** [comment]
stuff done
