### ISSUE TITLE
administrateur

### ISSUE THREAD

**Issue by 0x72D0** [0x72D0/JavaOverflow#34]
avoir un bouton quitter svp...

peut etre mettre un minimum de caractere pcq si on faist juste appliquer on le chance pour
" "

DUy

**Comment by BonGiovi44** [comment]
Boutton quitter est pas utile dans ce cas.

**Comment by 0x72D0** [comment]
effectivement, mais la prof voulait une maniere de quitter chaque fenetre sans toucher au x
