### ISSUE TITLE
Problème traitement réponse

### ISSUE THREAD

**Issue by waldo121** [0x72D0/JavaOverflow#42]
En entrant une mauvaise réponse à la question array_basic.txt, une exception est lancée et le message pour dire que la réponse est mauvaise n'apparait pas.

**Comment by 0x72D0** [comment]
lorsque ce probleme arrivera j'ai fait poper une fenetre disant d'avertir l'admin, c'est le plus qu'on peut faire c'est une exception propre au regex de Java

**Comment by 0x72D0** [comment]
#49
