### ISSUE TITLE
Methode createEleves() cause exception au lancement

### ISSUE THREAD

**Issue by BonGiovi44** [0x72D0/JavaOverflow#46]
Des que le programme est lance une exception est lance et la trace indique qu'il y a un probleme avec l'array qui est un nullpointer, c'est probablement parce qu'au debut il y a rien dans l'array.

**Comment by 0x72D0** [comment]
ben c'est normal, donc c'est bon ce n'est pas une exception qui nous bloque de toute facons

**Comment by 0x72D0** [comment]
si tu veut arreter cette exception rajoute un file User

**Comment by 0x72D0** [comment]
sry un dossier User

**Comment by 0x72D0** [comment]
bon maintenant le dossier User se cree automatiquement a la fermeture du programme, donc l'exception ne sera lancer qu'au debut
